[package]
name = "aether-voice"
version = "0.1.0"
authors = ["Cqdet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
audiopus_sys = "0.1"
deno_core = "0.69.0"